// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.0 (Build Build 184 04/29/2009)
// Created on Tue Nov 19 17:08:53 2019

zjw_bingxingjiafaqi zjw_bingxingjiafaqi_inst
(
	.A(A_sig) ,	// input [3:0] A_sig
	.B(B_sig) ,	// input [3:0] B_sig
	.Dout(Dout_sig) ,	// output [3:0] Dout_sig
	.Dout1(Dout1_sig) 	// output  Dout1_sig
);

